// Mocks generated by Mockito 5.0.10 from annotations
// in block/test/features/homepage/data/datasources/applications_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:block/features/homepage/data/datasources/applications.dart'
    as _i3;
import 'package:block/features/homepage/data/models/application.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeApplicationModel extends _i1.Fake implements _i2.ApplicationModel {}

/// A class which mocks [ApplicationDataSourceBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplicationDataSourceBase extends _i1.Mock
    implements _i3.ApplicationDataSourceBase {
  MockApplicationDataSourceBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ApplicationModel>> all() => (super.noSuchMethod(
      Invocation.method(#all, []),
      returnValue: Future<List<_i2.ApplicationModel>>.value(
          <_i2.ApplicationModel>[])) as _i4.Future<List<_i2.ApplicationModel>>);
  @override
  _i4.Future<_i2.ApplicationModel> find(int? id) =>
      (super.noSuchMethod(Invocation.method(#find, [id]),
              returnValue:
                  Future<_i2.ApplicationModel>.value(_FakeApplicationModel()))
          as _i4.Future<_i2.ApplicationModel>);
  @override
  _i4.Future<int> create(_i2.ApplicationModel? application) =>
      (super.noSuchMethod(Invocation.method(#create, [application]),
          returnValue: Future<int>.value(0)) as _i4.Future<int>);
  @override
  _i4.Future<void> update(int? id, _i2.ApplicationModel? application) =>
      (super.noSuchMethod(Invocation.method(#update, [id, application]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> delete(int? id) =>
      (super.noSuchMethod(Invocation.method(#delete, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
}
